#!/bin/bash

# Based on https://wiki.lineageos.org/signing_builds
# for LineageOS versions 19.1 and above
# Run `mka target-files-package otatools` before signing

set -e

key_path=/home/julian/android/aicp/rom-sign
ota_file=$OUT/${TARGET_PRODUCT}_v-20.0-${AICP_BUILDTYPE}_$(date "+%Y%m%d").zip
signed_target_files=$OUT/signed-target_files.zip

#croot

[ -f $signed_target_files ] && rm -f $signed_target_files
[ -f $ota_file ] && rm -f $ota_file

sign_target_files_apks -o -d "$key_path" \
    --extra_apks AdServicesApk.apk="$key_path"/releasekey \
    --extra_apks FederatedCompute.apk="$key_path"/releasekey \
    --extra_apks HalfSheetUX.apk="$key_path"/releasekey \
    --extra_apks HealthConnectBackupRestore.apk="$key_path"/releasekey \
    --extra_apks HealthConnectController.apk="$key_path"/releasekey \
    --extra_apks OsuLogin.apk="$key_path"/releasekey \
    --extra_apks SafetyCenterResources.apk="$key_path"/releasekey \
    --extra_apks ServiceConnectivityResources.apk="$key_path"/releasekey \
    --extra_apks ServiceUwbResources.apk="$key_path"/releasekey \
    --extra_apks ServiceWifiResources.apk="$key_path"/releasekey \
    --extra_apks WifiDialog.apk="$key_path"/releasekey \
    --extra_apks com.android.adbd.apex="$key_path"/com.android.adbd \
    --extra_apks com.android.adservices.apex="$key_path"/com.android.adservices \
    --extra_apks com.android.adservices.api.apex="$key_path"/com.android.adservices.api \
    --extra_apks com.android.appsearch.apex="$key_path"/com.android.appsearch \
    --extra_apks com.android.art.apex="$key_path"/com.android.art \
    --extra_apks com.android.bluetooth.apex="$key_path"/com.android.bluetooth \
    --extra_apks com.android.btservices.apex="$key_path"/com.android.btservices \
    --extra_apks com.android.cellbroadcast.apex="$key_path"/com.android.cellbroadcast \
    --extra_apks com.android.compos.apex="$key_path"/com.android.compos \
    --extra_apks com.android.configinfrastructure.apex="$key_path"/com.android.configinfrastructure \
    --extra_apks com.android.connectivity.resources.apex="$key_path"/com.android.connectivity.resources \
    --extra_apks com.android.conscrypt.apex="$key_path"/com.android.conscrypt \
    --extra_apks com.android.devicelock.apex="$key_path"/com.android.devicelock \
    --extra_apks com.android.extservices.apex="$key_path"/com.android.extservices \
    --extra_apks com.android.graphics.pdf.apex="$key_path"/com.android.graphics.pdf \
    --extra_apks com.android.hardware.biometrics.face.virtual.apex="$key_path"/com.android.hardware.biometrics.face.virtual \
    --extra_apks com.android.hardware.biometrics.fingerprint.virtual.apex="$key_path"/com.android.hardware.biometrics.fingerprint.virtual \
    --extra_apks com.android.hardware.boot.apex="$key_path"/com.android.hardware.boot \
    --extra_apks com.android.hardware.cas.apex="$key_path"/com.android.hardware.cas \
    --extra_apks com.android.hardware.wifi.apex="$key_path"/com.android.hardware.wifi \
    --extra_apks com.android.healthfitness.apex="$key_path"/com.android.healthfitness \
    --extra_apks com.android.hotspot2.osulogin.apex="$key_path"/com.android.hotspot2.osulogin \
    --extra_apks com.android.i18n.apex="$key_path"/com.android.i18n \
    --extra_apks com.android.ipsec.apex="$key_path"/com.android.ipsec \
    --extra_apks com.android.media.apex="$key_path"/com.android.media \
    --extra_apks com.android.media.swcodec.apex="$key_path"/com.android.media.swcodec \
    --extra_apks com.android.mediaprovider.apex="$key_path"/com.android.mediaprovider \
    --extra_apks com.android.nearby.halfsheet.apex="$key_path"/com.android.nearby.halfsheet \
    --extra_apks com.android.networkstack.tethering.apex="$key_path"/com.android.networkstack.tethering \
    --extra_apks com.android.neuralnetworks.apex="$key_path"/com.android.neuralnetworks \
    --extra_apks com.android.ondevicepersonalization.apex="$key_path"/com.android.ondevicepersonalization \
    --extra_apks com.android.os.statsd.apex="$key_path"/com.android.os.statsd \
    --extra_apks com.android.permission.apex="$key_path"/com.android.permission \
    --extra_apks com.android.resolv.apex="$key_path"/com.android.resolv \
    --extra_apks com.android.rkpd.apex="$key_path"/com.android.rkpd \
    --extra_apks com.android.runtime.apex="$key_path"/com.android.runtime \
    --extra_apks com.android.safetycenter.resources.apex="$key_path"/com.android.safetycenter.resources \
    --extra_apks com.android.scheduling.apex="$key_path"/com.android.scheduling \
    --extra_apks com.android.sdkext.apex="$key_path"/com.android.sdkext \
    --extra_apks com.android.support.apexer.apex="$key_path"/com.android.support.apexer \
    --extra_apks com.android.telephony.apex="$key_path"/com.android.telephony \
    --extra_apks com.android.telephonymodules.apex="$key_path"/com.android.telephonymodules \
    --extra_apks com.android.tethering.apex="$key_path"/com.android.tethering \
    --extra_apks com.android.tzdata.apex="$key_path"/com.android.tzdata \
    --extra_apks com.android.uwb.apex="$key_path"/com.android.uwb \
    --extra_apks com.android.uwb.resources.apex="$key_path"/com.android.uwb.resources \
    --extra_apks com.android.virt.apex="$key_path"/com.android.virt \
    --extra_apks com.android.vndk.current.apex="$key_path"/com.android.vndk.current \
    --extra_apks com.android.vndk.current.on_vendor.apex="$key_path"/com.android.vndk.current.on_vendor \
    --extra_apks com.android.wifi.apex="$key_path"/com.android.wifi \
    --extra_apks com.android.wifi.dialog.apex="$key_path"/com.android.wifi.dialog \
    --extra_apks com.android.wifi.resources.apex="$key_path"/com.android.wifi.resources \
    --extra_apks com.google.pixel.camera.hal.apex="$key_path"/com.google.pixel.camera.hal \
    --extra_apks com.google.pixel.vibrator.hal.apex="$key_path"/com.google.pixel.vibrator.hal \
    --extra_apks com.qorvo.uwb.apex="$key_path"/com.qorvo.uwb \
    --extra_apex_payload_key com.android.adbd.apex="$key_path"/com.android.adbd.pem \
    --extra_apex_payload_key com.android.adservices.apex="$key_path"/com.android.adservices.pem \
    --extra_apex_payload_key com.android.adservices.api.apex="$key_path"/com.android.adservices.api.pem \
    --extra_apex_payload_key com.android.appsearch.apex="$key_path"/com.android.appsearch.pem \
    --extra_apex_payload_key com.android.art.apex="$key_path"/com.android.art.pem \
    --extra_apex_payload_key com.android.bluetooth.apex="$key_path"/com.android.bluetooth.pem \
    --extra_apex_payload_key com.android.btservices.apex="$key_path"/com.android.btservices.pem \
    --extra_apex_payload_key com.android.cellbroadcast.apex="$key_path"/com.android.cellbroadcast.pem \
    --extra_apex_payload_key com.android.compos.apex="$key_path"/com.android.compos.pem \
    --extra_apex_payload_key com.android.configinfrastructure.apex="$key_path"/com.android.configinfrastructure.pem \
    --extra_apex_payload_key com.android.connectivity.resources.apex="$key_path"/com.android.connectivity.resources.pem \
    --extra_apex_payload_key com.android.conscrypt.apex="$key_path"/com.android.conscrypt.pem \
    --extra_apex_payload_key com.android.devicelock.apex="$key_path"/com.android.devicelock.pem \
    --extra_apex_payload_key com.android.extservices.apex="$key_path"/com.android.extservices.pem \
    --extra_apex_payload_key com.android.graphics.pdf.apex="$key_path"/com.android.graphics.pdf.pem \
    --extra_apex_payload_key com.android.hardware.biometrics.face.virtual.apex="$key_path"/com.android.hardware.biometrics.face.virtual.pem \
    --extra_apex_payload_key com.android.hardware.biometrics.fingerprint.virtual.apex="$key_path"/com.android.hardware.biometrics.fingerprint.virtual.pem \
    --extra_apex_payload_key com.android.hardware.boot.apex="$key_path"/com.android.hardware.boot.pem \
    --extra_apex_payload_key com.android.hardware.cas.apex="$key_path"/com.android.hardware.cas.pem \
    --extra_apex_payload_key com.android.hardware.wifi.apex="$key_path"/com.android.hardware.wifi.pem \
    --extra_apex_payload_key com.android.healthfitness.apex="$key_path"/com.android.healthfitness.pem \
    --extra_apex_payload_key com.android.hotspot2.osulogin.apex="$key_path"/com.android.hotspot2.osulogin.pem \
    --extra_apex_payload_key com.android.i18n.apex="$key_path"/com.android.i18n.pem \
    --extra_apex_payload_key com.android.ipsec.apex="$key_path"/com.android.ipsec.pem \
    --extra_apex_payload_key com.android.media.apex="$key_path"/com.android.media.pem \
    --extra_apex_payload_key com.android.media.swcodec.apex="$key_path"/com.android.media.swcodec.pem \
    --extra_apex_payload_key com.android.mediaprovider.apex="$key_path"/com.android.mediaprovider.pem \
    --extra_apex_payload_key com.android.nearby.halfsheet.apex="$key_path"/com.android.nearby.halfsheet.pem \
    --extra_apex_payload_key com.android.networkstack.tethering.apex="$key_path"/com.android.networkstack.tethering.pem \
    --extra_apex_payload_key com.android.neuralnetworks.apex="$key_path"/com.android.neuralnetworks.pem \
    --extra_apex_payload_key com.android.ondevicepersonalization.apex="$key_path"/com.android.ondevicepersonalization.pem \
    --extra_apex_payload_key com.android.os.statsd.apex="$key_path"/com.android.os.statsd.pem \
    --extra_apex_payload_key com.android.permission.apex="$key_path"/com.android.permission.pem \
    --extra_apex_payload_key com.android.resolv.apex="$key_path"/com.android.resolv.pem \
    --extra_apex_payload_key com.android.rkpd.apex="$key_path"/com.android.rkpd.pem \
    --extra_apex_payload_key com.android.runtime.apex="$key_path"/com.android.runtime.pem \
    --extra_apex_payload_key com.android.safetycenter.resources.apex="$key_path"/com.android.safetycenter.resources.pem \
    --extra_apex_payload_key com.android.scheduling.apex="$key_path"/com.android.scheduling.pem \
    --extra_apex_payload_key com.android.sdkext.apex="$key_path"/com.android.sdkext.pem \
    --extra_apex_payload_key com.android.support.apexer.apex="$key_path"/com.android.support.apexer.pem \
    --extra_apex_payload_key com.android.telephony.apex="$key_path"/com.android.telephony.pem \
    --extra_apex_payload_key com.android.telephonymodules.apex="$key_path"/com.android.telephonymodules.pem \
    --extra_apex_payload_key com.android.tethering.apex="$key_path"/com.android.tethering.pem \
    --extra_apex_payload_key com.android.tzdata.apex="$key_path"/com.android.tzdata.pem \
    --extra_apex_payload_key com.android.uwb.apex="$key_path"/com.android.uwb.pem \
    --extra_apex_payload_key com.android.uwb.resources.apex="$key_path"/com.android.uwb.resources.pem \
    --extra_apex_payload_key com.android.virt.apex="$key_path"/com.android.virt.pem \
    --extra_apex_payload_key com.android.vndk.current.apex="$key_path"/com.android.vndk.current.pem \
    --extra_apex_payload_key com.android.vndk.current.on_vendor.apex="$key_path"/com.android.vndk.current.on_vendor.pem \
    --extra_apex_payload_key com.android.wifi.apex="$key_path"/com.android.wifi.pem \
    --extra_apex_payload_key com.android.wifi.dialog.apex="$key_path"/com.android.wifi.dialog.pem \
    --extra_apex_payload_key com.android.wifi.resources.apex="$key_path"/com.android.wifi.resources.pem \
    --extra_apex_payload_key com.google.pixel.camera.hal.apex="$key_path"/com.google.pixel.camera.hal.pem \
    --extra_apex_payload_key com.google.pixel.vibrator.hal.apex="$key_path"/com.google.pixel.vibrator.hal.pem \
    --extra_apex_payload_key com.qorvo.uwb.apex="$key_path"/com.qorvo.uwb.pem \
    $OUT/obj/PACKAGING/target_files_intermediates/*-target_files*.zip \
    $signed_target_files

ota_from_target_files -k "$key_path"/releasekey \
    --block --backup=true \
    $signed_target_files \
    $ota_file

sha256sum $ota_file > ${ota_file}.sha256sum
